# Generated by Django 4.2.1 on 2023-05-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNeighborsClassifier', '0004_aimodel_alter_csvdata_csv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='ia_model',
            field=models.CharField(choices=[('model1', 'Model 1'), ('model2', 'Model 2'), ('model3', 'Model 3')], max_length=100),
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
