# Generated by Django 4.2.1 on 2023-05-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KNeighborsClassifier', '0005_alter_csvdata_ia_model_delete_aimodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='owner',
        ),
    ]
